import { existsSync } from "node:fs";
import { mkdir, readdir, readFile, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import { spawn, spawnSync } from "node:child_process";
import net from "node:net";
import { loadConfig, updateConfig } from "./config.js";
import { appendLog } from "./logging.js";
import { getPaths } from "./paths.js";
import { findSiteForCwd } from "./sites.js";
import type { CommandSpec, PhpConfig, PhpExtensionStatus, PhpSettingsStatus, ServiceAction, ServiceStatus, Site } from "./types.js";

const generatedPhpIniHeader = "; Generated by laraboxs for the app-local PHP runtime.";

export function phpFastCgiPort(version: string): number {
  const digits = version.replace(/\D/g, "");
  const suffix = Number.parseInt(digits || "84", 10);
  return 9000 + suffix;
}

export function phpBinaryPath(version: string): string {
  const bundled = path.join(getPaths().phpRoot, version, "php.exe");
  return existsSync(bundled) ? bundled : "php";
}

export function phpCgiBinaryPath(version: string): string {
  return path.join(getPaths().phpRoot, version, "php-cgi.exe");
}

export function phpIniPath(version: string): string {
  return path.join(getPaths().phpRoot, version, "php.ini");
}

export function buildPhpCommand(version: string, args: string[]): CommandSpec {
  const iniPath = phpIniPath(version);
  return {
    command: phpBinaryPath(version),
    args: existsSync(iniPath) ? ["-c", iniPath, ...args] : args
  };
}

export async function selectedPhpVersionForCwd(cwd = process.cwd()): Promise<string> {
  try {
    const site: Site = await findSiteForCwd(cwd);
    return site.phpVersion;
  } catch {
    const { loadConfig } = await import("./config.js");
    return (await loadConfig()).globalPhpVersion;
  }
}

export async function runPhp(args: string[], cwd = process.cwd()): Promise<number> {
  const version = await selectedPhpVersionForCwd(cwd);
  await ensurePhpIni(version);
  const command = buildPhpCommand(version, args);
  const child = spawn(command.command, command.args, {
    cwd,
    stdio: "inherit",
    shell: false
  });

  return new Promise((resolve) => {
    child.on("error", () => resolve(1));
    child.on("exit", (code) => resolve(code ?? 1));
  });
}

export async function ensurePhpFastCgiWorkers(): Promise<void> {
  const config = await loadConfig();
  await Promise.all(config.phpVersions.map((version) => startPhpFastCgiWorker(version)));
}

export async function runPhpFastCgi(action: ServiceAction): Promise<ServiceStatus> {
  const config = await loadConfig();

  if (action === "stop" || action === "restart") {
    await Promise.all(config.phpVersions.map((version) => stopPhpFastCgiWorker(version)));
  }

  if (action === "start" || action === "restart") {
    await Promise.all(config.phpVersions.map((version) => startPhpFastCgiWorker(version)));
  }

  await appendLog("php", `FastCGI ${action} requested`);
  return getPhpFastCgiStatus();
}

export async function getPhpSettings(version?: string): Promise<PhpSettingsStatus> {
  const config = await loadConfig();
  const selectedVersion = version ?? config.globalPhpVersion;
  const available = await availablePhpExtensions(selectedVersion);
  const enabled = new Set(config.php.enabledExtensions);
  const names = Array.from(new Set([...available.map((extension) => extension.name), ...config.php.enabledExtensions])).sort();

  return {
    version: selectedVersion,
    iniPath: phpIniPath(selectedVersion),
    settings: config.php,
    extensions: names.map((name) => {
      const match = available.find((extension) => extension.name === name);
      return {
        name,
        available: Boolean(match),
        enabled: enabled.has(name),
        dll: match?.dll
      };
    })
  };
}

export async function updatePhpSettings(settings: Partial<PhpConfig>): Promise<PhpConfig> {
  const nextSettings = validatePhpSettingsPatch(settings);
  const config = await updateConfig((current) => {
    current.php = {
      ...current.php,
      ...nextSettings,
      enabledExtensions: nextSettings.enabledExtensions ?? current.php.enabledExtensions
    };
  });
  await ensurePhpIniForConfiguredVersions();
  await appendLog("php", "PHP settings updated");
  return config.php;
}

export async function ensurePhpIniForConfiguredVersions(): Promise<void> {
  const config = await loadConfig();
  await Promise.all(config.phpVersions.map((version) => ensurePhpIni(version)));
}

export async function getPhpFastCgiStatus(): Promise<ServiceStatus> {
  const config = await loadConfig();
  const checks = await Promise.all(
    config.phpVersions.map(async (version) => ({
      version,
      port: phpFastCgiPort(version),
      binaryExists: existsSync(phpCgiBinaryPath(version)),
      running: await canConnect("127.0.0.1", phpFastCgiPort(version), 200)
    }))
  );

  const runningCount = checks.filter((check) => check.running).length;
  const missing = checks.filter((check) => !check.binaryExists).map((check) => check.version);
  const state = runningCount === checks.length && checks.length > 0 ? "running" : runningCount === 0 ? "stopped" : "unknown";
  const workerMessage = checks.length ? `${runningCount}/${checks.length} FastCGI workers running.` : "No PHP versions configured.";
  const missingMessage = missing.length ? `Missing php-cgi.exe for PHP ${missing.join(", ")}.` : "";

  return {
    name: "php",
    state,
    version: config.globalPhpVersion,
    port: phpFastCgiPort(config.globalPhpVersion),
    logPath: path.join(getPaths().logs, "php-fastcgi.log"),
    message: [workerMessage, missingMessage].filter(Boolean).join(" ")
  };
}

async function startPhpFastCgiWorker(version: string): Promise<void> {
  const port = phpFastCgiPort(version);
  const binary = phpCgiBinaryPath(version);

  if (await canConnect("127.0.0.1", port, 200)) {
    return;
  }

  if (!existsSync(binary)) {
    await appendLog("php", `php-cgi.exe not found for PHP ${version}: ${binary}`);
    return;
  }

  const iniPath = await ensurePhpIni(version);
  await mkdir(getPaths().logs, { recursive: true });
  const child = spawn(binary, ["-c", iniPath, "-b", `127.0.0.1:${port}`], {
    cwd: path.dirname(binary),
    detached: true,
    stdio: "ignore",
    shell: false,
    windowsHide: true
  });
  child.once("error", (error) => {
    void appendLog("php", `FastCGI ${version} failed: ${error.message}`);
  });
  child.unref();
  await writeFile(phpFastCgiPidPath(version), String(child.pid), "utf8");
  await waitForPort(port, 3000);
  await appendLog("php", `FastCGI ${version} started on 127.0.0.1:${port}`);
}

export async function ensurePhpIni(version: string): Promise<string> {
  const root = path.join(getPaths().phpRoot, version);
  const iniPath = phpIniPath(version);
  await mkdir(root, { recursive: true });
  if (existsSync(iniPath)) {
    const current = await readFile(iniPath, "utf8");
    if (!current.startsWith(generatedPhpIniHeader)) {
      return iniPath;
    }
  }

  const extDir = path.join(root, "ext");
  const config = await loadConfig();
  const available = new Map((await availablePhpExtensions(version)).map((extension) => [extension.name, extension]));
  const extensions = config.php.enabledExtensions.filter((extension) => Boolean(available.get(extension)?.dll));
  const builtInExtensions = config.php.enabledExtensions.filter((extension) => available.get(extension)?.builtIn && !available.get(extension)?.dll);
  const unavailableExtensions = config.php.enabledExtensions.filter((extension) => !available.has(extension));
  const ini = [
    generatedPhpIniHeader,
    `extension_dir="${toPhpIniPath(extDir)}"`,
    "cgi.force_redirect=0",
    "cgi.fix_pathinfo=1",
    "fastcgi.impersonate=1",
    "date.timezone=UTC",
    "error_reporting=E_ALL & ~E_DEPRECATED & ~E_USER_DEPRECATED",
    `memory_limit=${config.php.memoryLimit}`,
    `upload_max_filesize=${config.php.uploadMaxFilesize}`,
    `post_max_size=${config.php.postMaxSize}`,
    `max_execution_time=${config.php.maxExecutionTime}`,
    `max_input_vars=${config.php.maxInputVars}`,
    "variables_order=GPCS",
    ...extensions.map((extension) => `extension=${extension}`),
    ...builtInExtensions.map((extension) => `; extension=${extension} is built into this PHP version.`),
    ...unavailableExtensions.map((extension) => `; extension=${extension} skipped by laraboxs: php_${extension}.dll was not found in this PHP version's ext folder.`),
    ""
  ].join("\n");

  await writeFile(iniPath, ini, "utf8");
  await appendLog("php", `generated php.ini for PHP ${version}`);
  return iniPath;
}

async function availablePhpExtensions(version: string): Promise<Array<{ name: string; dll?: string; builtIn?: boolean }>> {
  const extDir = path.join(getPaths().phpRoot, version, "ext");
  const byName = new Map<string, { name: string; dll?: string; builtIn?: boolean }>();

  try {
    const entries = await readdir(extDir, { withFileTypes: true });
    for (const extension of entries
      .filter((entry) => entry.isFile() && /^php_[A-Za-z0-9_]+\.dll$/i.test(entry.name))
      .map((entry) => ({
        name: entry.name.replace(/^php_/i, "").replace(/\.dll$/i, "").toLowerCase(),
        dll: path.join(extDir, entry.name)
      }))) {
      byName.set(extension.name, extension);
    }
  } catch {
    // PHP may not be installed yet, or the runtime may not have an ext directory.
  }

  for (const extension of builtInPhpExtensions(version)) {
    const current = byName.get(extension);
    byName.set(extension, current ? { ...current, builtIn: true } : { name: extension, builtIn: true });
  }

  return Array.from(byName.values()).sort((a, b) => a.name.localeCompare(b.name));
}

function builtInPhpExtensions(version: string): string[] {
  const binary = path.join(getPaths().phpRoot, version, "php.exe");
  if (!existsSync(binary)) {
    return [];
  }

  const result = spawnSync(binary, ["-n", "-m"], { encoding: "utf8", timeout: 2500, windowsHide: true });
  if (result.status !== 0 || result.error) {
    return [];
  }

  return Array.from(
    new Set(
      `${result.stdout ?? ""}\n${result.stderr ?? ""}`
        .split(/\r?\n/)
        .map((line) => line.trim().toLowerCase())
        .filter((line) => /^[a-z0-9_]+$/.test(line))
    )
  ).sort();
}

function validatePhpSettingsPatch(settings: Partial<PhpConfig>): Partial<PhpConfig> {
  const patch: Partial<PhpConfig> = {};

  if (settings.memoryLimit !== undefined) {
    patch.memoryLimit = validatePhpSize(settings.memoryLimit, "memory_limit");
  }
  if (settings.uploadMaxFilesize !== undefined) {
    patch.uploadMaxFilesize = validatePhpSize(settings.uploadMaxFilesize, "upload_max_filesize");
  }
  if (settings.postMaxSize !== undefined) {
    patch.postMaxSize = validatePhpSize(settings.postMaxSize, "post_max_size");
  }
  if (settings.maxExecutionTime !== undefined) {
    patch.maxExecutionTime = validatePositiveInteger(settings.maxExecutionTime, "max_execution_time");
  }
  if (settings.maxInputVars !== undefined) {
    patch.maxInputVars = validatePositiveInteger(settings.maxInputVars, "max_input_vars");
  }
  if (settings.enabledExtensions !== undefined) {
    patch.enabledExtensions = Array.from(
      new Set(
        settings.enabledExtensions.map((extension) => {
          if (typeof extension !== "string" || !/^[A-Za-z0-9_]+$/.test(extension)) {
            throw new Error("PHP extension names may contain only letters, numbers, and underscores.");
          }
          return extension.toLowerCase();
        })
      )
    ).sort();
  }

  return patch;
}

function validatePhpSize(value: string, name: string): string {
  const trimmed = value.trim().toUpperCase();
  if (!/^\d+(?:K|M|G)?$/.test(trimmed)) {
    throw new Error(`${name} must look like 128M, 1G, or 512K.`);
  }
  return trimmed;
}

function validatePositiveInteger(value: number, name: string): number {
  if (!Number.isInteger(value) || value < 0 || value > 1_000_000) {
    throw new Error(`${name} must be an integer between 0 and 1000000.`);
  }
  return value;
}

function toPhpIniPath(filePath: string): string {
  return path.resolve(filePath).replace(/\\/g, "/");
}

async function stopPhpFastCgiWorker(version: string): Promise<void> {
  const pidPath = phpFastCgiPidPath(version);
  try {
    const pid = Number((await readFile(pidPath, "utf8")).trim());
    if (Number.isFinite(pid) && pid > 0) {
      process.kill(pid);
    }
  } catch {
    // The worker may already be gone or may have been started outside laraboxs.
  }
  await rm(pidPath, { force: true });
  await appendLog("php", `FastCGI ${version} stop requested`);
}

function phpFastCgiPidPath(version: string): string {
  return path.join(getPaths().logs, `php-cgi-${version}.pid`);
}

async function waitForPort(port: number, timeoutMs: number): Promise<void> {
  const startedAt = Date.now();
  while (Date.now() - startedAt < timeoutMs) {
    if (await canConnect("127.0.0.1", port, 200)) {
      return;
    }
    await new Promise((resolve) => setTimeout(resolve, 100));
  }
}

function canConnect(host: string, port: number, timeout: number): Promise<boolean> {
  return new Promise((resolve) => {
    const socket = net.createConnection({ host, port });
    const finish = (result: boolean) => {
      socket.destroy();
      resolve(result);
    };
    socket.setTimeout(timeout);
    socket.once("connect", () => finish(true));
    socket.once("timeout", () => finish(false));
    socket.once("error", () => finish(false));
  });
}
